# Generated by Django 2.1.7 on 2019-03-25 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gomaku', '0003_auto_20190323_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.IntegerField(default=-1),
        ),
    ]
